/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_noelmartinez;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author noelg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_habitantes = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jt_apellido = new javax.swing.JTextField();
        jt_edad = new javax.swing.JTextField();
        rb_f = new javax.swing.JRadioButton();
        rb_m = new javax.swing.JRadioButton();
        jt_vocacion = new javax.swing.JTextField();
        rb_siU = new javax.swing.JRadioButton();
        rb_noU = new javax.swing.JRadioButton();
        rb_siC = new javax.swing.JRadioButton();
        rb_noC = new javax.swing.JRadioButton();
        bt_habitante = new javax.swing.JButton();
        jt_nacionalidad = new javax.swing.JTextField();
        jd_pais = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombrePais = new javax.swing.JTextField();
        jdate_fechaFundacion = new com.toedter.calendar.JDateChooser();
        jt_himno = new javax.swing.JTextField();
        bt_color = new javax.swing.JButton();
        bt_pais = new javax.swing.JButton();
        jp_menu1 = new javax.swing.JPopupMenu();
        jm_crearmujer = new javax.swing.JMenuItem();
        jm_crearhombre = new javax.swing.JMenuItem();
        jm_modificarpais = new javax.swing.JMenuItem();
        bg_genero = new javax.swing.ButtonGroup();
        bg_titulo = new javax.swing.ButtonGroup();
        bg_corona = new javax.swing.ButtonGroup();
        jp_menu2 = new javax.swing.JPopupMenu();
        jm_agregarhabitante = new javax.swing.JMenuItem();
        jp_menu3 = new javax.swing.JPopupMenu();
        jm_modificar = new javax.swing.JMenuItem();
        jm_eliminar = new javax.swing.JMenuItem();
        jm_expulsar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_masculinos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_femeninas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_paises = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_coronavirus = new javax.swing.JTree();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_paises = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jd_habitantes.setMinimumSize(new java.awt.Dimension(998, 540));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Nacionalidad");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Vocacion");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("¿ Tiene titulo universitario ?");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("¿ Tiene Corona Virus ?");

        bg_genero.add(rb_f);
        rb_f.setSelected(true);
        rb_f.setText("Femenino");

        bg_genero.add(rb_m);
        rb_m.setText("Masculino");

        bg_titulo.add(rb_siU);
        rb_siU.setSelected(true);
        rb_siU.setText("Si");

        bg_titulo.add(rb_noU);
        rb_noU.setText("No");

        bg_corona.add(rb_siC);
        rb_siC.setSelected(true);
        rb_siC.setText("Si");

        bg_corona.add(rb_noC);
        rb_noC.setText("No");

        bt_habitante.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bt_habitante.setText("Crear Habitante");
        bt_habitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_habitanteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_habitantesLayout = new javax.swing.GroupLayout(jd_habitantes.getContentPane());
        jd_habitantes.getContentPane().setLayout(jd_habitantesLayout);
        jd_habitantesLayout.setHorizontalGroup(
            jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_habitantesLayout.createSequentialGroup()
                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombre)
                            .addComponent(jt_apellido)
                            .addComponent(jt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_nacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                        .addGap(184, 184, 184)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_habitantesLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jt_vocacion))
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(jd_habitantesLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(rb_f)
                                .addGap(8, 8, 8)
                                .addComponent(rb_m))
                            .addGroup(jd_habitantesLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                                        .addComponent(rb_siC)
                                        .addGap(44, 44, 44)
                                        .addComponent(rb_noC))
                                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                                        .addComponent(rb_siU)
                                        .addGap(40, 40, 40)
                                        .addComponent(rb_noU))))))
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(bt_habitante)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jd_habitantesLayout.setVerticalGroup(
            jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_habitantesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(rb_f)
                    .addComponent(rb_m)
                    .addComponent(jt_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jt_vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(bt_habitante))
                    .addGroup(jd_habitantesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_siU)
                            .addComponent(rb_noU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jd_habitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_noC)
                            .addComponent(rb_siC))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jd_pais.setMinimumSize(new java.awt.Dimension(978, 574));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Fecha de Fundacion");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Nombre del Himno Nacional");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Color de la Bandera");

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        bt_pais.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bt_pais.setText("Crear Pais");
        bt_pais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_paisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(170, 170, 170)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_himno)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(bt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jt_himno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate_fechaFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(bt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout jd_paisLayout = new javax.swing.GroupLayout(jd_pais.getContentPane());
        jd_pais.getContentPane().setLayout(jd_paisLayout);
        jd_paisLayout.setHorizontalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_paisLayout.setVerticalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jm_crearmujer.setText("Crear Mujer");
        jm_crearmujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_crearmujerActionPerformed(evt);
            }
        });
        jp_menu1.add(jm_crearmujer);

        jm_crearhombre.setText("Crear Hombre");
        jm_crearhombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_crearhombreActionPerformed(evt);
            }
        });
        jp_menu1.add(jm_crearhombre);

        jm_modificarpais.setText("Modificar Pais");
        jm_modificarpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_modificarpaisActionPerformed(evt);
            }
        });
        jp_menu1.add(jm_modificarpais);

        jm_agregarhabitante.setText("Agregar ");
        jm_agregarhabitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregarhabitanteActionPerformed(evt);
            }
        });
        jp_menu2.add(jm_agregarhabitante);

        jm_modificar.setText("Modificar");
        jm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_modificarActionPerformed(evt);
            }
        });
        jp_menu3.add(jm_modificar);

        jm_eliminar.setText("Eliminar");
        jm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarActionPerformed(evt);
            }
        });
        jp_menu3.add(jm_eliminar);

        jm_expulsar.setText("Expulsar");
        jm_expulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_expulsarActionPerformed(evt);
            }
        });
        jp_menu3.add(jm_expulsar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_masculinos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_masculinos);

        jl_femeninas.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_femeninas);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_paises.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_paisesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_paises);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Infectadas");
        jt_coronavirus.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt_coronavirus);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Masculinos");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Femeninas");

        jl_paises.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_paises);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Paises");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(jLabel14)
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(276, 276, 276))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Crear Habitante");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Crear Pais");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        jd_habitantes.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        jd_pais.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        Color color;
        bt_color.setBackground(JColorChooser.showDialog(jMenu1, "Ingrese el color de la bandera", Color.yellow));
        color = bt_color.getBackground();
    }//GEN-LAST:event_bt_colorMouseClicked

    private void bt_habitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_habitanteMouseClicked
        String tieneCorona = "";
        String tieneTitulo = "";
        String mujer = "";
        String hombre = "";
        if (rb_f.isSelected()) {
            mujer = jt_nombre.getText();
        } else {
            hombre = jt_nombre.getText();
        }
        if (rb_siC.isSelected()) {
            tieneCorona = "Si";
        } else {
            tieneCorona = "No";
        }
        if (rb_siU.isSelected()) {
            tieneTitulo = "Si";
        } else {
            tieneTitulo = "No";
        }

        if (rb_f.isSelected()) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_femeninas.getModel();
            modelo.addElement(new Persona(jt_nacionalidad.getText(), jt_nombre.getText(), jt_apellido.getText(), Integer.parseInt(jt_edad.getText()), mujer, jt_vocacion.getText(), tieneTitulo, tieneCorona));
            jl_femeninas.setModel(modelo);
            jt_nombre.setText("");
            jt_nacionalidad.setText("");
            jt_apellido.setText("");
            jt_edad.setText("");
            jt_vocacion.setText("");
        }

        if (rb_m.isSelected()) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_masculinos.getModel();
            modelo.addElement(new Persona(jt_nacionalidad.getText(), jt_nombre.getText(), jt_apellido.getText(), Integer.parseInt(jt_edad.getText()), mujer, jt_vocacion.getText(), tieneTitulo, tieneCorona));
            jl_masculinos.setModel(modelo);
            jt_nombre.setText("");
            jt_nacionalidad.setText("");
            jt_apellido.setText("");
            jt_edad.setText("");
            jt_vocacion.setText("");
        }

        JOptionPane.showMessageDialog(this, "Habitante creado con exito!");
    }//GEN-LAST:event_bt_habitanteMouseClicked

    private void bt_paisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_paisMouseClicked
        DefaultListModel modelo
                = (DefaultListModel) jl_paises.getModel();

        modelo.addElement(new Pais(tf_nombrePais.getText(), jdate_fechaFundacion.getDate(), jt_himno.getText(), Color.darkGray));

        DefaultTreeModel m = (DefaultTreeModel) jt_paises.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_pais;
        nodo_pais = new DefaultMutableTreeNode(new Pais(tf_nombrePais.getText(), jdate_fechaFundacion.getDate(), jt_himno.getText(), Color.darkGray));

        raiz.add(nodo_pais);
        m.reload();
        JOptionPane.showMessageDialog(this, "Pais creado con exito!");


    }//GEN-LAST:event_bt_paisMouseClicked

    private void jm_crearmujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_crearmujerActionPerformed
        DefaultTreeModel m
                = (DefaultTreeModel) jt_paises.getModel();
        String sex = "Mujer";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();
    }//GEN-LAST:event_jm_crearmujerActionPerformed

    private void jm_crearhombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_crearhombreActionPerformed
        DefaultTreeModel m
                = (DefaultTreeModel) jt_paises.getModel();
        String sex = "Hombre";
        nodo_seleccionado.add(new DefaultMutableTreeNode(sex));
        m.reload();
    }//GEN-LAST:event_jm_crearhombreActionPerformed

    private void jt_paisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_paisesMouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_paises.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_paises.setSelectionRow(row);
            Object v1
                    = jt_paises.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            //nodo_seleccionado = (DefaultMutableTreeNode) v1;
            switch (nodo_seleccionado.getLevel()) {
                case 1:
                    jp_menu1.show(evt.getComponent(), evt.getX(), evt.getY());
                    break;
                case 2:
                    jp_menu2.show(evt.getComponent(), evt.getX(), evt.getY());
                    break;
                case 3:
                    jp_menu3.show(evt.getComponent(), evt.getX(), evt.getY());
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_jt_paisesMouseClicked

    private void jm_agregarhabitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregarhabitanteActionPerformed
        if (jl_masculinos.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_paises.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_masculinos.getModel();

            String nacionalidad, nombre, apellido;
            int edad;
            nacionalidad
                    = ((Persona) modeloLISTA.get(
                            jl_masculinos.getSelectedIndex())).
                            getNacionalidad();

            nombre = ((Persona) modeloLISTA.get(
                    jl_masculinos.getSelectedIndex())).
                    getNombre();
            edad = ((Persona) modeloLISTA.get(
                    jl_masculinos.getSelectedIndex())).
                    getEdad();
            apellido = ((Persona) modeloLISTA.get(jl_masculinos.getSelectedIndex())).getApellido();

            int centinela = -1;

            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(nombre + " " + apellido);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Persona(nacionalidad, nombre, apellido, edad));
                n.add(p);
                nodo_seleccionado.add(n);
                jl_masculinos.clearSelection();
            }  // fin if

        } else if (jl_femeninas.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_paises.getModel();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_femeninas.getModel();

            String nacionalidad, nombre, apellido;
            int edad;
            nacionalidad
                    = ((Persona) modeloLISTA.get(
                            jl_femeninas.getSelectedIndex())).
                            getNacionalidad();

            nombre = ((Persona) modeloLISTA.get(
                    jl_femeninas.getSelectedIndex())).
                    getNombre();
            edad = ((Persona) modeloLISTA.get(
                    jl_femeninas.getSelectedIndex())).
                    getEdad();
            apellido = ((Persona) modeloLISTA.get(jl_femeninas.getSelectedIndex())).getApellido();

            int centinela = -1;
            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(nombre + " " + apellido);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Persona(nacionalidad, nombre, apellido, edad));
                n.add(p);
                nodo_seleccionado.add(n);
            }  // fin if
            jl_femeninas.clearSelection();
            modeloARBOL.reload();

        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jm_agregarhabitanteActionPerformed

    private void jm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_modificarActionPerformed
        DefaultTreeModel m
                = (DefaultTreeModel) jt_paises.getModel();
        nodo_seleccionado.setUserObject(JOptionPane.showInputDialog("nombre"));
        m.reload();
    }//GEN-LAST:event_jm_modificarActionPerformed

    private void jm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) jt_paises.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_jm_eliminarActionPerformed

    private void jm_modificarpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_modificarpaisActionPerformed
         DefaultTreeModel m
                = (DefaultTreeModel) jt_paises.getModel();
        nodo_seleccionado.setUserObject(JOptionPane.showInputDialog("Nuevo Pais"));
        m.reload();
    }//GEN-LAST:event_jm_modificarpaisActionPerformed

    private void jm_expulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_expulsarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro que desea expulsar a la persona ?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) jt_paises.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_jm_expulsarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    DefaultMutableTreeNode nodo_seleccionado;
    Pais pais_seleccionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_corona;
    private javax.swing.ButtonGroup bg_genero;
    private javax.swing.ButtonGroup bg_titulo;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_habitante;
    private javax.swing.JButton bt_pais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_habitantes;
    private javax.swing.JDialog jd_pais;
    private com.toedter.calendar.JDateChooser jdate_fechaFundacion;
    private javax.swing.JList<String> jl_femeninas;
    private javax.swing.JList<String> jl_masculinos;
    private javax.swing.JList<String> jl_paises;
    private javax.swing.JMenuItem jm_agregarhabitante;
    private javax.swing.JMenuItem jm_crearhombre;
    private javax.swing.JMenuItem jm_crearmujer;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JMenuItem jm_expulsar;
    private javax.swing.JMenuItem jm_modificar;
    private javax.swing.JMenuItem jm_modificarpais;
    private javax.swing.JPopupMenu jp_menu1;
    private javax.swing.JPopupMenu jp_menu2;
    private javax.swing.JPopupMenu jp_menu3;
    private javax.swing.JTextField jt_apellido;
    private javax.swing.JTree jt_coronavirus;
    private javax.swing.JTextField jt_edad;
    private javax.swing.JTextField jt_himno;
    private javax.swing.JTextField jt_nacionalidad;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTree jt_paises;
    private javax.swing.JTextField jt_vocacion;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_noC;
    private javax.swing.JRadioButton rb_noU;
    private javax.swing.JRadioButton rb_siC;
    private javax.swing.JRadioButton rb_siU;
    private javax.swing.JTextField tf_nombrePais;
    // End of variables declaration//GEN-END:variables
}
